        migrationBuilder.InsertData(
             table: "LookupCountry",
             columns: new[] { "Id", "Name", "RequiresVisa", "Active" },
             values: new object[,]
             {
                    { 1, "British", true, 1 },
                    { 2, "Afghani", true, 1 },
                    { 3, "Albanian", true, 1 },
                    { 4, "Algerian", true, 1 },
                    { 5, "American", true, 1 },
                    { 6, "American Samoan", true, 1 },
                    { 7, "Andorran", true, 1 },
                    { 8, "Angolan", true, 1 },
                    { 9, "Anguillan", true, 1 },
                    { 10, "Antarctican", true, 1 },
                    { 11, "Antiguan", true, 1 },
                    { 12, "Argentinian", true, 1 },
                    { 13, "Armenian", true, 1 },
                    { 14, "Aruban", true, 1 },
                    { 15, "Australian", true, 1 },
                    { 16, "Austrian", true, 1 },
                    { 17, "Azerbaijani", true, 1 },
                    { 18, "Bahamian", true, 1 },
                    { 19, "Bahraini", true, 1 },
                    { 20, "Bangladeshi", true, 1 },
                    { 21, "Barbadian", true, 1 },
                    { 22, "Barthelemois", true, 1 },
                    { 23, "Bermudian", true, 1 },
                    { 24, "Belarusian", true, 1 },
                    { 25, "Belgian", true, 1 },
                    { 26, "Belizean", true, 1 },
                    { 27, "Beninese", true, 1 },
                    { 28, "Bhutanese", true, 1 },
                    { 29, "Bolivian", true, 1 },
                    { 30, "Bosnian/Herzego", true, 1 },
                    { 31, "Brazilian", true, 1 },
                    { 32, "Bruneian", true, 1 },
                    { 33, "Bulgarian", true, 1 },
                    { 34, "Burkinabe", true, 1 },
                    { 35, "Burmese", true, 1 },
                    { 36, "Burundian", true, 1 },
                    { 37, "Cambodian", true, 1 },
                    { 38, "Cameroonian", true, 1 },
                    { 39, "Canadian", true, 1 },
                    { 40, "Cape Verdian", true, 1 },
                    { 41, "Caymanian", true, 1 },
                    { 42, "Central African", true, 1 },
                    { 43, "Chadian", true, 1 },
                    { 44, "Channel Islande", true, 1 },
                    { 45, "Chilean", true, 1 },
                    { 46, "Chinese", true, 1 },
                    { 47, "Christmas Islan", true, 1 },
                    { 48, "Cocos Islander", true, 1 },
                    { 49, "Colombian", true, 1 },
                    { 50, "Comoran", true, 1 },
                    { 51, "Congolese", true, 1 },
                    { 52, "Cook Islander", true, 1 },
                    { 53, "Costa Rican", true, 1 },
                    { 54, "Croatian", true, 1 },
                    { 55, "Cuban", true, 1 },
                    { 56, "Cypriot", true, 1 },
                    { 57, "Czech", true, 1 },
                    { 58, "Danish", true, 1 },
                    { 59, "Djiboutian", true, 1 },
                    { 60, "Dominican", true, 1 },
                    { 61, "Dutch", true, 1 },
                    { 62, "Dutch Antillean", true, 1 },
                    { 63, "East Timorese", true, 1 },
                    { 64, "Ecuadorian", true, 1 },
                    { 65, "Egyptian", true, 1 },
                    { 66, "Emirati", true, 1 },
                    { 67, "Equatorial Guin", true, 1 },
                    { 68, "Eritrean", true, 1 },
                    { 69, "Estonian", true, 1 },
                    { 70, "Ethiopian", true, 1 },
                    { 71, "Falkland Island", true, 1 },
                    { 72, "Faroese", true, 1 },
                    { 73, "Fijian", true, 1 },
                    { 74, "Filipino", true, 1 },
                    { 75, "Finnish", true, 1 },
                    { 76, "French", true, 1 },
                    { 77, "French Guianese", true, 1 },
                    { 78, "French Polynesi", true, 1 },
                    { 79, "Gabonese", true, 1 },
                    { 80, "Gambian", true, 1 },
                    { 81, "Georgian", true, 1 },
                    { 82, "German", true, 1 },
                    { 83, "Ghanaian", true, 1 },
                    { 84, "Gibraltarian", true, 1 },
                    { 85, "Greek", true, 1 },
                    { 86, "Greenlander", true, 1 },
                    { 87, "Grenadian", true, 1 },
                    { 88, "Guadeloupian", true, 1 },
                    { 89, "Guamanian", true, 1 },
                    { 90, "Guatemalan", true, 1 },
                    { 91, "Guinea-Bissauan", true, 1 },
                    { 92, "Guinean", true, 1 },
                    { 93, "Guyanese", true, 1 },
                    { 94, "Haitian", true, 1 },
                    { 95, "Honduran", true, 1 },
                    { 96, "Hungarian", true, 1 },
                    { 97, "Icelandic", true, 1 },
                    { 98, "I-Kiribati", true, 1 },
                    { 99, "Indian", true, 1},
                    { 100, "Indonesian", true, 1 },
                    { 101, "Iranian", true, 1 },
                    { 102, "Iraqi", true, 1 },
                    { 103, "Irish", true, 1 },
                    { 104, "Israeli", true, 1 },
                    { 105, "Italian", true, 1 },
                    { 106, "Ivorian", true, 1 },
                    { 107, "Jamaican", true, 1 },
                    { 108, "Japanese", true, 1 },
                    { 109, "Jordanian", true, 1 },
                    { 110, "Kazakhstani", true, 1 },
                    { 111, "Kenyan", true, 1 },
                    { 112, "Kirghiztani", true, 1 },
                    { 113, "Kittian/Nevis\'n", true, 1 },
                    { 114, "Kosovan", true, 1 },
                    { 115, "Kuwaiti", true, 1 },
                    { 116, "Lao Or Laotian", true, 1 },
                    { 117, "Latvian", true, 1 },
                    { 118, "Lebanese", true, 1 },
                    { 119, "Liberian", true, 1 },
                    { 120, "Libyan", true, 1 },
                    { 121, "Liechtensteiner", true, 1 },
                    { 122, "Lithuanian", true, 1 },
                    { 123, "Luxembourgish", true, 1 },
                    { 124, "Macedonian", true, 1 },
                    { 125, "Mahorais", true, 1 },
                    { 126, "Malagasy", true, 1 },
                    { 127, "Malawian", true, 1 },
                    { 128, "Malaysian", true, 1 },
                    { 129, "Maldivan", true, 1 },
                    { 130, "Malian", true, 1 },
                    { 131, "Maltese", true, 1 },
                    { 132, "Manx", true, 1 },
                    { 133, "Marshallese", true, 1 },
                    { 134, "Martiniquais", true, 1 },
                    { 135, "Mauritanian", true, 1 },
                    { 136, "Mauritian", true, 1 },
                    { 137, "Mexican", true, 1 },
                    { 138, "Micronesian", true, 1 },
                    { 139, "Moldovan", true, 1 },
                    { 140, "Monegasque", true, 1 },
                    { 141, "Mongolian", true, 1 },
                    { 142, "Montenegran", true, 1 },
                    { 143, "Montserratian", true, 1 },
                    { 144, "Moroccan", true, 1 },
                    { 145, "Mosotho", true, 1 },
                    { 146, "Botswanian", true, 1 },
                    { 147, "Mozambican", true, 1 },
                    { 148, "Namibian", true, 1 },
                    { 149, "Nauruan", true, 1 },
                    { 150, "Nepalese", true, 1 },
                    { 151, "New Caledonian", true, 1 },
                    { 152, "New Zealander", true, 1 },
                    { 153, "Nicaraguan", true, 1 },
                    { 154, "Nigerien", true, 1 },
                    { 155, "Niuean", true, 1 },
                    { 156, "Ni-Vanuatu", true, 1 },
                    { 157, "Norfolk Islande", true, 1 },
                    { 158, "North Korean", true, 1 },
                    { 159, "Northern Marina Islands", true, 1 },
                    { 160, "Norwegian", true, 1 },
                    { 161, "Norwegian", true, 1 },
                    { 162, "Omani", true, 1 },
                    { 163, "Pakistani", true, 1 },
                    { 164, "Palauan", true, 1 },
                    { 165, "Palestinian", true, 1 },
                    { 166, "Panamanian", true, 1 },
                    { 167, "Papua New Guine", true, 1 },
                    { 168, "Paraguayan", true, 1 },
                    { 169, "Peruvian", true, 1 },
                    { 170, "Pitcairn Island", true, 1 },
                    { 171, "Polish", true, 1 },
                    { 172, "Portuguese", true, 1 },
                    { 173, "Puerto Rican", true, 1 },
                    { 174, "Qatari", true, 1 },
                    { 175, "Reunionese", true, 1 },
                    { 176, "Romanian", true, 1 },
                    { 177, "Russian", true, 1 },
                    { 178, "Rwandan", true, 1 },
                    { 179, "Sahraoui", true, 1 },
                    { 180, "Saint Helenian", true, 1 },
                    { 181, "Saint Lucian", true, 1 },
                    { 182, "Saint Martiners", true, 1 },
                    { 183, "Saint Vincentia", true, 1 },
                    { 184, "Salvadoran", true, 1 },
                    { 185, "Samoan", true, 1 },
                    { 186, "San Marinese", true, 1 },
                    { 187, "Sao Tomean", true, 1 },
                    { 188, "Saudi Arabian", true, 1 },
                    { 189, "Senegalese", true, 1 },
                    { 190, "Serb/Montenegrn", true, 1 },
                    { 191, "Serbian", true, 1 },
                    { 192, "Seychellois", true, 1 },
                    { 193, "Sierra Leonean", true, 1 },
                    { 194, "Singaporean", true, 1 },
                    { 195, "Slovakian", true, 1 },
                    { 196, "Slovenian", true, 1 },
                    { 197, "Solomon Islande", true, 1 },
                    { 198, "Somalian", true, 1 },
                    { 199, "South African", true, 1 },
                    { 200, "South Korean", true, 1 },
                    { 201, "South Sudaneses", true, 1 },
                    { 202, "Spanish", true, 1 },
                    { 203, "Sri Lankan", true, 1 },
                    { 204, "Sudanese", true, 1 },
                    { 205, "Surinamer", true, 1 },
                    { 206, "Swazi", true, 1 },
                    { 207, "Swedish", true, 1 },
                    { 208, "Swiss", true, 1 },
                    { 209, "Syrian", true, 1 },
                    { 210, "Taiwanese", true, 1 },
                    { 211, "Tajik/Tadzhik", true, 1 },
                    { 212, "Tanzanian", true, 1 },
                    { 213, "TC Islander", true, 1 },
                    { 214, "Thai", true, 1 },
                    { 215, "Togolese", true, 1 },
                    { 216, "Tokelan", true, 1 },
                    { 217, "Tongan", true, 1 },
                    { 218, "Trinidadian", true, 1 },
                    { 219, "Tunisian", true, 1 },
                    { 220, "Turkish", true, 1 },
                    { 221, "Turkmeni", true, 1 },
                    { 222, "Tuvaluan", true, 1 },
                    { 223, "Ugandan", true, 1 },
                    { 224, "Ukrainian", true, 1 },
                    { 225, "Uruguayan", true, 1 },
                    { 226, "Uzbeki", true, 1 },
                    { 227, "Venezuelan", true, 1 },
                    { 228, "Vietnamese", true, 1 },
                    { 229, "Virgin Islander", true, 1 },
                    { 230, "Wallis\'n/Futun", true, 1 },
                    { 231, "Yemenite", true, 1 },
                    { 232, "Zambian", true, 1 },
                    { 233, "Zimbabwean", true, 1 }
             });
